apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec: 
  containers:
  - name: nginx
    image: nginx:perl

  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 19']