apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:                                  # Labels to the ReplicaSet
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:                               # Labels to the Pod
      labels:
        tier: frontend
    spec:
      containers:
      - name: 
        image: docker.io/nginx:perl
