apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-np
  labels:
    app: nginx-np
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-np
  template:
    metadata:
      labels:
        app: nginx-np
    spec:
      containers:
      - name: nginx
        image: nginx:perl
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-np-svc
spec:
  type: NodePort
  selector:
    app: nginx-np
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007