apiVersion: v1
kind: Namespace
metadata:
  name: expense
--- 
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: expense
spec:
  hard:
    pods: "10"                      # Maximum number of Pods
    requests.cpu: "400"               # Total CPU requests across all Pods
    requests.memory: "2000Gi"          # Total memory requests across all Pods
    limits.cpu: "500"                 # Total CPU limits across all Pods
    limits.memory: "4000Gi"           # Total memory limits across all Pods
 
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mem-cpu-demo
  labels:
    app: nginx
spec:
  strategy:
    # type: Recreate
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:perl
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "5000Mi"
            cpu: "1000m"
          limits:
            memory: "6000Mi"
            cpu: "2000m"