apiVersion: v1
kind: ServiceAccount
metadata:
  name: expense-sa
 
--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: namespace-reader
rules:
- apiGroups: [""] 
  resources: ["*"]
  verbs: ["get", "list"] 

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: expense-sa
  namespace: default
roleRef:
  kind: Role 
  name: namespace-reader
  apiGroup: rbac.authorization.k8s.io


# When the user attempts to do something apart from the allowed actions, they will receive an error message similar to the following:
# Error from server (Forbidden): error when creating "sample.yaml": pods is forbidden: User "system:serviceaccount:default:expense-sa" cannot create resource "pods" in API group "" in the namespace "default"