apiVersion: v1
kind: Namespace
metadata:
  name: mzapp

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: dmzapp

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mznginx-deployment
  namespace: mzapp
  labels:
    app: mznginx
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 5
  selector:
    matchLabels:
      app: mznginx
  template:
    metadata:
      labels:
        app: mznginx
    spec:
      containers:
      - name: nginx
        image: nginx:perl
        ports:
        - containerPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmznginx-deployment
  namespace: dmzapp
  labels:
    app: dmznginx
    
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 5
  selector:
    matchLabels:
      app: dmznginx
  template:
    metadata:
      labels:
        app: dmznginx
    spec:
      containers:
      - name: nginx
        image: nginx:perl
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mznginx-deployment-svc
  namespace: mzapp
spec:
  selector:
    app: mznginx
  ports:
    - protocol: TCP
      port: 80                  # Port exposed by the service
      targetPort: 80  

--- 

apiVersion: v1
kind: Service
metadata:
  name: dmznginx-deployment-svc
  namespace: dmzapp
spec:
  selector:
    app: dmznginx
  ports:
    - protocol: TCP
      port: 80                  # Port exposed by the service
      targetPort: 80  



--- 

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-traffic
  namespace: mzapp
spec:
  podSelector: {}  # Selects all pods in the namespace
  policyTypes:
    - Ingress
    - Egress