appName: mysql
replicas: 1
containerPort: 3306
serviceType: ClusterIP 
imageVersion: docker.io/mysql:8.0
env:
  app_repo: "https://github.com/expenseapp-001/expense-backend.git"
  db_host: mysql-svc
  db_user: root
  db_password: ExpenseApp@1
  schema_file: /app/schema/backend.sql
schemaInjectionEnabled: true