appName: mysql
replicas: 1
containerPort: 3306
serviceType: ClusterIP 
imageVersion: docker.io/mysql:8.0
env:
  - name: app_repo
    value: "https://github.com/expenseapp-001/expense-backend.git"
  - name: db_host
    value: mysql-svc
  - name: db_user
    value: root
  - name: db_password
    value: ExpenseApp@1 
  - name: schema_file
    value: /app/schema/backend.sql
schemaInjectionEnabled: true